version: '3.4'

services:
  default:
    image: ${DOCKER_REGISTRY}default
    build:
      context: .
      dockerfile: Default/Dockerfile

  custom:
    image: ${DOCKER_REGISTRY}custom
    build:
      context: .
      dockerfile: Custom/Dockerfile


  kestrelapp:
    image: ${DOCKER_REGISTRY}kestrelapp
    build:
      context: .
      dockerfile: KestrelApp/Dockerfile

